Zadanie1: Zdefiniuj dowolne dwie macierze kwadratowe $A$ i $B$ o wymiarach (3,3) (trzy kolumny i trzy wiersze). Przekonaj się, że mnożenie macierzy nie jest na ogół przemienne, tj. $AB$ i $BA$ to różne macierze.

In [1]:
import numpy as np

A = np.random.randint(0, 10, (3, 3)) #całkowiete 0-9
B = np.random.randint(0, 10, (3, 3))

print(np.dot(A,B))
print(np.dot(B,A))

[[72 68 53]
 [66 68 17]
 [16 48 40]]
[[48 28 64]
 [57 48 61]
 [12 60 84]]


Zadanie2: Wyznacz macierz $B^4+AB+6B^{-1}A$, gdzie $A$ i $B$ zdefiniowane w poprzednim zadaniu.

In [41]:
C = np.linalg.matrix_power(B, 4) + np.dot(A,B) + 6 * np.dot(np.linalg.inv(B),A)
print(C)

[[10460.20689655 12456.13793103  9270.10344828]
 [11763.79310345 14095.86206897 10301.89655172]
 [ 9430.96551724 11703.31034483  9276.48275862]]


Zadanie3: Zdefiniuj dane uczące  X=np.array([1,2,3,4,5])  oraz  Y=np.array([−1,3,13,29,51]) . Zakładamy, że pomiędzy  X  i  Y  istnieje przybliżona zależność $Y=aX^2+bX+c$. Zbuduj model przewidujący wartość parametrów  a,b,c  w oparciu o  X  i  Y. Następnie wyznacz przewidywaną wartość dla  x=6 .

In [63]:
X=np.array([1,2,3,4,5])
Y=np.array([-1,3,13,29,51])

a = 4.0
b = -6.0
c = 0.0

#Funkcja modelu
def forward(x):
    return a * (x**2) + b * x + c

#Loss fucntion
def loss(y, y_pred):
    return np.mean(((y_pred - y)**2))

#Gradient
def gradient(x, y, y_pred):
    return np.mean(2*(x**2)*(y_pred - y)), np.mean(2*x*(y_pred - y)), np.mean(2*(y_pred - y)) #pochodne (po funkcji kosztu)

print(f'Ile wynosi f(5): {forward(5):.3f}')
print(f'Ile wynosi f(6): {forward(6):.3f}')

#trenowanie
learning_rate = 0.004 #współczynnik uczenia 
n_iters = 1000 #liczba iteracji

for epoch in range(n_iters):
    y_pred = forward(X) #przewidywane wartości dla X
    l = loss(Y, y_pred) #wartość funkcji kosztu
    dl = gradient(X, Y, y_pred) #gradient
    a -= learning_rate * dl[0]    #aktualizujemy parametr a
    b -= learning_rate * dl[1]    ##aktualizujemy parametr b
    c -= learning_rate * dl[2]    ##aktualizujemy parametr c
    
    if epoch % 200 == 0: #wypritowanie parametów co 200 krok
        print(f'epoch {epoch+1}: a = {a:.3f}, b = {b:.3f}, c = {c:.3f}, loss = {l:.8f}')
  
print(f'Ile wynosi f(5) po trenowaniu: {forward(5):.3f}') #do ustalenia paramtrów, 
                                                        #powinno byc jak najbliżej 51
print(f'Ile wynosi f(6) po trenowaniu: {forward(6):.3f}')


Ile wynosi f(5): 70.000
Ile wynosi f(6): 108.000
epoch 1: a = 2.882, b = -6.248, c = -0.056, loss = 101.80000000
epoch 201: a = 3.061, b = -5.196, c = 0.719, loss = 0.10908894
epoch 401: a = 3.006, b = -4.996, c = 0.880, loss = 0.00514906
epoch 601: a = 2.995, b = -4.956, c = 0.917, loss = 0.00046024
epoch 801: a = 2.992, b = -4.949, c = 0.928, loss = 0.00023004
Ile wynosi f(5) po trenowaniu: 50.990
Ile wynosi f(6) po trenowaniu: 78.955


Zadanie4: Zdefiniuj dane uczące  X=np.array([−3,−2,−1,0,1,2,3])  oraz  Y=np.array([27,−32,−13,0,−5,32,243]) . Zakładamy, że pomiędzy  X  i  Y  istnieje przybliżona zależność  $Y=aX^4+bX^3+cX^2+dX+e$. Zbuduj model przewidujący wartość parametrów  a,b,c,d,e  w oparciu o  X  i  Y . Przetestuj trzy rodzaje parametrów, wyświetlając za każdym razem tylko 5 epok z modelu (w równych odstępach czasu). Skomentuj otrzymane wyniki

- parametry początkowe: a=0, b=0, c=0, d=0, e=0; learning_rate=0.01; n_iters = 10

In [72]:
X=np.array([-3,-2,-1,0,1,2,3]) 
Y=np.array([27,-32,-13,0,-5,32,243])

a = 0.0
b = 0.0
c = 0.0
d = 0.0
e = 0.0

def forward(x):
    return a* (x**4) + b*(x**3) + c*(x**2) + d*x + e

def loss(y, y_pred):
    return np.mean(((y_pred - y)**2))

def gradient(x, y, y_pred):
    return np.mean(2*(x**4)*(y_pred - y)), np.mean(2*(x**3)*(y_pred - y)), np.mean(2*(x**2)*(y_pred - y)), np.mean(2*x*(y_pred - y)), np.mean(2*(y_pred -y))#pochodne (po funkcji kosztu)

learning_rate = 0.01
n_iters = 10 

for epoch in range(n_iters):
    y_pred = forward(X) 
    l = loss(Y, y_pred)
    dl = gradient(X, Y, y_pred) 
    a -= learning_rate * dl[0]    
    b -= learning_rate * dl[1]    
    c -= learning_rate * dl[2]   
    d -= learning_rate * dl[3] 
    e -= learning_rate * dl[4]
    
    if epoch % 2 == 0: 
        print(f'epoch {epoch+1}: a = {a:.3f}, b = {b:.3f}, c = {c:.3f}, loss = {l:.8f}')
  
print(f'Ile wynosi f(3) po trenowaniu: {forward(3):.3f}') #dla 3 powinno być 243
print(f'Ile wynosi f(2) po trenowaniu: {forward(2):.3f}') #dla 2 powinno być 32

#bardzo zły wynik, mało iteracji, cięzko coś stwierdzić o innych parametrach na tej podstawie


epoch 1: a = 62.434, b = 18.149, c = 6.891, loss = 8860.00000000
epoch 3: a = 90119.630, b = 188.738, c = 10502.794, loss = 10971787004.49891090
epoch 5: a = 133555795.921, b = 2407.461, c = 15566613.915, loss = 24096626835551156.00000000
epoch 7: a = 197931233544.355, b = 31264.827, c = 23069904428.300, loss = 52924826724148046725120.00000000
epoch 9: a = 293336380263515.750, b = 406592.392, c = 34189865528285.430, loss = 116241883769402444936499953664.00000000
Ile wynosi f(3) po trenowaniu: -926704622090009984.000
Ile wynosi f(2) po trenowaniu: -186108350863026880.000


- parametry początkowe: a=0, b=0, c=0, d=0, e=0; learning_rate=0.0001; n_iters = 10

In [73]:
X=np.array([-3,-2,-1,0,1,2,3]) 
Y=np.array([27,-32,-13,0,-5,32,243])

a = 0.0
b = 0.0
c = 0.0
d = 0.0
e = 0.0

def forward(x):
    return a* (x**4) + b*(x**3) + c*(x**2) + d*x + e

def loss(y, y_pred):
    return np.mean(((y_pred - y)**2))

def gradient(x, y, y_pred):
    return np.mean(2*(x**4)*(y_pred - y)), np.mean(2*(x**3)*(y_pred - y)), np.mean(2*(x**2)*(y_pred - y)), np.mean(2*x*(y_pred - y)), np.mean(2*(y_pred -y))#pochodne (po funkcji kosztu)

learning_rate = 0.0001 
n_iters = 10 

for epoch in range(n_iters):
    y_pred = forward(X) 
    l = loss(Y, y_pred) 
    dl = gradient(X, Y, y_pred)
    a -= learning_rate * dl[0]    
    b -= learning_rate * dl[1]    
    c -= learning_rate * dl[2]   
    d -= learning_rate * dl[3] 
    e -= learning_rate * dl[4]
    
    if epoch % 2 == 0: 
        print(f'epoch {epoch+1}: a = {a:.3f}, b = {b:.3f}, c = {c:.3f}, loss = {l:.8f}')
  
print(f'Ile wynosi f(3) po trenowaniu: {forward(3):.3f}') #dla 3 powinno być 242
print(f'Ile wynosi f(2) po trenowaniu: {forward(2):.3f}') #dla 2 powinno być 32

#wynik dużo lepszy! Współczynnik uczenia pomógł, zwiększenie ilości iteracji 
#powinno nas jeszcze bardziej przybliżyć do 243 lub 32

epoch 1: a = 0.624, b = 0.181, c = 0.069, loss = 8860.00000000
epoch 3: a = 1.231, b = 0.520, c = 0.132, loss = 3909.86850594
epoch 5: a = 1.454, b = 0.828, c = 0.150, loss = 2813.14452827
epoch 7: a = 1.536, b = 1.108, c = 0.152, loss = 2307.23739952
epoch 9: a = 1.567, b = 1.363, c = 0.148, loss = 1942.15494443
Ile wynosi f(3) po trenowaniu: 169.336
Ile wynosi f(2) po trenowaniu: 37.982


- parametry początkowe: a=0, b=0, c=0, d=0, e=0; learning_rate=0.0001; n_iters = 10000

In [74]:
X=np.array([-3,-2,-1,0,1,2,3]) 
Y=np.array([27,-32,-13,0,-5,32,243])

a = 0.0
b = 0.0
c = 0.0
d = 0.0
e = 0.0

def forward(x):
    return a* (x**4) + b*(x**3) + c*(x**2) + d*x + e

def loss(y, y_pred):
    return np.mean(((y_pred - y)**2))

def gradient(x, y, y_pred):
    return np.mean(2*(x**4)*(y_pred - y)), np.mean(2*(x**3)*(y_pred - y)), np.mean(2*(x**2)*(y_pred - y)), np.mean(2*x*(y_pred - y)), np.mean(2*(y_pred -y))#pochodne (po funkcji kosztu)

learning_rate = 0.0001
n_iters = 10000

for epoch in range(n_iters):
    y_pred = forward(X) 
    l = loss(Y, y_pred)
    dl = gradient(X, Y, y_pred) 
    a -= learning_rate * dl[0]    
    b -= learning_rate * dl[1]    
    c -= learning_rate * dl[2]   
    d -= learning_rate * dl[3] 
    e -= learning_rate * dl[4] 
    
    if epoch % 2000 == 0: 
        print(f'epoch {epoch+1}: a = {a:.3f}, b = {b:.3f}, c = {c:.3f}, loss = {l:.8f}')
  
print(f'Ile wynosi f(3) po trenowaniu: {forward(3):.3f}')
print(f'Ile wynosi f(2) po trenowaniu: {forward(2):.3f}')

#Bardzo dobry wynik, tak jak przypuszczałam zwiększenie ilości iteracji pomogło


epoch 1: a = 0.624, b = 0.181, c = 0.069, loss = 8860.00000000
epoch 2001: a = 2.236, b = 3.951, c = -5.153, loss = 53.66383643
epoch 4001: a = 2.545, b = 3.961, c = -7.692, loss = 14.96772300
epoch 6001: a = 2.695, b = 3.968, c = -8.945, loss = 6.30163472
epoch 8001: a = 2.771, b = 3.974, c = -9.602, loss = 4.01116693
Ile wynosi f(3) po trenowaniu: 242.609
Ile wynosi f(2) po trenowaniu: 33.937


- parametry początkowe: a=2.7, b=4.2, c=-11.9, d=0.1, e=0; learning_rate=0.0001; n_iters = 10000

In [75]:
X=np.array([-3,-2,-1,0,1,2,3]) 
Y=np.array([27,-32,-13,0,-5,32,243])

a = 2.7
b = 4.2
c = -11.9
d = 0.1
e = 0.0

def forward(x):
    return a* (x**4) + b*(x**3) + c*(x**2) + d*x + e

def loss(y, y_pred):
    return np.mean(((y_pred - y)**2))

def gradient(x, y, y_pred):
    return np.mean(2*(x**4)*(y_pred - y)), np.mean(2*(x**3)*(y_pred - y)), np.mean(2*(x**2)*(y_pred - y)), np.mean(2*x*(y_pred - y)), np.mean(2*(y_pred -y))#pochodne (po funkcji kosztu)
    
print(f'Ile wynosi f(5): {forward(3):.3f}')

learning_rate = 0.0001 
n_iters = 10000 

for epoch in range(n_iters):
    y_pred = forward(X)
    l = loss(Y, y_pred) 
    dl = gradient(X, Y, y_pred) 
    a -= learning_rate * dl[0]    
    b -= learning_rate * dl[1]    
    c -= learning_rate * dl[2]   
    d -= learning_rate * dl[3] 
    e -= learning_rate * dl[4]
    
    if epoch % 2000 == 0: 
        print(f'epoch {epoch+1}: a = {a:.3f}, b = {b:.3f}, c = {c:.3f}, loss = {l:.8f}')
  
print(f'Ile wynosi f(3) po trenowaniu: {forward(3):.3f}') #dla 2 powinno być 242
print(f'Ile wynosi f(2) po trenowaniu: {forward(2):.3f}') #dla 2 powinno być 32

#Najlepszy wynik, zmiana parametrów początkowych pozwoliła bardziej zbliżyć się do oczekiwanych wyników

Ile wynosi f(5): 225.300
epoch 1: a = 2.812, b = 4.190, c = -11.887, loss = 172.22285714
epoch 2001: a = 2.992, b = 3.993, c = -11.926, loss = 0.00845286
epoch 4001: a = 2.995, b = 3.994, c = -11.954, loss = 0.00302564
epoch 6001: a = 2.997, b = 3.995, c = -11.968, loss = 0.00153028
epoch 8001: a = 2.998, b = 3.996, c = -11.975, loss = 0.00097174
Ile wynosi f(3) po trenowaniu: 242.988
Ile wynosi f(2) po trenowaniu: 32.044


Zadanie5. Utwórz dwa tensory jednowymiarowe  x=tensor([1,2,3,4,5,6])  oraz  y=tensor([7,8,3,−1.,−2,2]) . Następnie wyznacz nowy tensor wg przepisu  $z=x^3+2y$. Utwórz dwa nowe tensory (2D - o wymiarach 2 na 3 oraz 3D - o wymiarach 2,1,3 odpowiednio) poprzez zmianę wymiaru  z .

In [ ]:
import torch
x= torch.tensor([1,2,3,4,5,6])
y= torch.tensor([7,8,3,-1.,-2,2])

z = x**3 + 2*y
print(z)

z2 = z.view([2,-1])
print(z2)

z3 = z.view([2,1,3]) # 2 'bloki', każdy z 1 wierszem i 3 kolumnai.
print(z3)

tensor([ 15.,  24.,  33.,  62., 121., 220.])
tensor([[ 15.,  24.,  33.],
        [ 62., 121., 220.]])
tensor([[[ 15.,  24.,  33.]],

        [[ 62., 121., 220.]]])


<h4> Zadanie6: Wyjaśnij poniższe liniki kodu i otrzymany wynik (łącznie z uzyskanymi wartościami w x.grad)


In [ ]:
x = torch.tensor([-3.0,4,1], requires_grad=True) #tensor z opcją śledzenia 
z = x**3 #podnosimy kazdy elemet x do 3 potegi
print(z)
r = z.sum() #sumujemy elemety z z (64-26=38)
print(r)
r.backward() #obliczamy gradienty (3x**2)
print(x.grad) #printujemy gradienty  x

#tensor([27., 48.,  3.]) = [3*(-3)^2 3*4^2, 3*1^2] = [27, 48, 3]

tensor([-27.,  64.,   1.], grad_fn=<PowBackward0>)
tensor(38., grad_fn=<SumBackward0>)
tensor([27., 48.,  3.])


<h4> Zadanie7: Wyjaśnij poniższe liniki kodu i otrzymany wynik (łącznie z uzyskanymi wartościami w x.grad)

In [ ]:
x = torch.tensor([-3.0,4,1], requires_grad=True) #tworzymy tensory z opcją śledzenia
y = torch.tensor([2.0,0,-1], requires_grad=True)
z = (x**2)*y #podnosimy każdy elem z x do 2 potegi i mnożymy przez odpowiadające elementy z y
r = z.sum() #sumujemy elemety z z (18-1=17)
print(r)
r.backward() #obliczamy gradienty 
print(x.grad) #wyswietlamy gradiety względem x (2xy)
#tensor([-12.,   0.,  -2.]) = [2*(-3)*2, 2*4*0, 2*1*(-1)] = [-12, 0, -2]

tensor([18.,  0., -1.], grad_fn=<MulBackward0>)
tensor(17., grad_fn=<SumBackward0>)
tensor([-12.,   0.,  -2.])
